using System;
using UnityEngine;
using UnityEngine.SceneManagement;

public partial class DungeonGenerator
{
    void Awake()
    {
        InitializeConnections();
        PersistentGameSettings.ApplySavedToDungeonGenerator(this);
        SceneManager.sceneLoaded -= OnSceneLoaded;
        SceneManager.sceneLoaded += OnSceneLoaded;
        buildComplete = false;  // do this really really early
        Awake_Tilemap();
    }

    void OnDestroy()
    {
        //Debug.Log($"[DG] OnDestroy in scene '{gameObject.scene.name}' (id {GetInstanceID()})");
        SceneManager.sceneLoaded -= OnSceneLoaded;
        OnDestroy_Tilemap();
    }

    void OnSceneLoaded(Scene s, LoadSceneMode m)
    {
        InitializeConnections();   // rebind after scene changes
    }

    void InitializeConnections()
    {
        if (!dir)
        {
            dir = FindFirstObjectByType<Dir>(FindObjectsInactive.Include);
            if (!dir) Debug.LogError($"[DungeonGenerator.InitializeConnections] dir not found!");
        }

        // --- DungeonSettings (ScriptableObject) ---
        if (!cfg)
        {
            cfg = dir.cfg;
            if (!cfg) Debug.LogError($"[DungeonGenerator.InitializeConnections] cfg not valid from dir!");
        }

        if (hf==null)
        {
            hf = dir.gen.hf;
        }
    }

    // ------------------------------------- //
    // Start is called by Unity before the first frame update
    public void Start()
    {
        if (cfg == null)
        {
            Debug.LogWarning("DungeonGenerator: dungeonSettings is NULL!");
        }
        //else
        //{
        //    cfg.LogMe("DungeonGenerator.Start");
        //}

        // load the mission parameters...

        if (dir.dungeonBuildSettingsUI != null)
            dir.dungeonBuildSettingsUI.LoadMapSettingsByName(PersistentGameSettings.GetSelectedMapPresetName(dir.dungeonBuildSettingsUI.subFolder));

        PersistentGameSettings.ApplySavedGraphicsToDungeonGenerator(this);

        Debug.Log("DungeonGenerator ready. Map generation will start when Run Simulation is pressed.");
    }

    public void BeginNewSimulation()
    {
        // Initialize randomizer either with preselected seed, or one generated by clock.
        if (cfg.randomizeSeed) cfg.seed = (int)(DateTime.Now.Ticks % int.MaxValue);
        UnityEngine.Random.InitState(cfg.seed);
        Debug.Log("DungeonGenerator starting with seed: " + cfg.seed);

        RegenerateDungeon();
    }

    // Enables the Splash screen in front of DungeonGenerator so start menu hides building process.
    public static void EnableSplash()
    {
        Scene scene = SceneManager.GetActiveScene();
        GameObject[] roots = scene.GetRootGameObjects();

        foreach (var go in roots)
        {
            if (go.name == "Splash")
            {
                Debug.Log("Enabling Splash while DungeonGenerator running in background.");
                go.SetActive(true);
                return;
            }
        }
        Debug.LogWarning("Did not find object Splash to enable Splash Screen in DungeonGenerator.");
        return; // didn't find it.
    }

    public void MainMenuClosed()
    {
        // Start Game Music and SFX
        dir.audioPlayer.PlayClip("Mission Home Sweet Home");
    }
}
